export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_USER_DATA = "GET_USER_DATA";
export const CLEAR_USER_DATA = "CLEAR_USER_DATA";
export const UPDATE_USER_DATA = "UPDATE_USER_DATA";
export const GET_TIME_DATA = "GET_TIME_DATA";
